minimum_pre_commit_version: "2.7.1"
# default_stages: [commit, push]
# fail_fast: true
repos:
  # Git-related
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0 # Use the ref you want to point at
    hooks:
      - id: forbid-new-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0 # Use the ref you want to point at
    hooks:
      - id: git-dirty

  # Reformatting (should generally come before any file format or other checks, because reformatting can change things)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: dist/ # apparently sometimes the build adds in whitespace, so this can cause the git repo to be dirty unnecessarily
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: .babelrc

  - repo: https://github.com/prettier/prettier
    rev: 2.1.1 # pick a git hash / tag to point to
    hooks:
      - id: prettier
        exclude: dist/

  # Safety/Security Issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0 # Use the ref you want to point at
    hooks:
      - id: detect-private-key

  # Invalid File Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        name: general-large-file-check
        args: ["--maxkb=123"]
        exclude: package-lock.json
      - id: check-added-large-files
        name: large-files-in-dist
        args: ["--maxkb=200"]
        files: dist/
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
  # Linting
  - repo: https://github.com/NanoSurface-Biomedical/pre-commit-pylint
    rev: "d805cc60bb5290c2f1ca869d5f1d5e2be720f3fa" # pick a git hash / tag to point to
    hooks:
      - id: vuejs-check-no-console-log-statments
        exclude: dist
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.9.0
    hooks:
      - id: eslint
        exclude: (dist/)
        files: \.(vue)|(js)$
        types: [file]
        additional_dependencies:
          - babel-eslint@10.1.0
          - eslint@7.14.0
          - eslint-config-google@0.14.0
          - eslint-config-prettier@6.14.0
          - eslint-config-standard@14.1.1
          - eslint-loader@4.0.2
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jest@24.1.3
          - eslint-plugin-node@11.1.0
          - eslint-plugin-promise@4.2.1
          - eslint-plugin-snakecasejs@2.2.0
          - eslint-plugin-standard@5.0.0
          - eslint-plugin-vue@7.1.0
