minimum_pre_commit_version: 2.9.3
# default_stages: [commit, push]
# fail_fast: true
repos:
  # Git-related
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: forbid-new-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5 # Use the ref you want to point at
    hooks:
      - id: git-dirty

  # Reformatting (should generally come before any file format or other checks, because reformatting can change things)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: .babelrc

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--print-width=110]

  # Safety/Security Issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: detect-private-key

  # Invalid File Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        name: general-large-file-check
        args: ["--maxkb=123"]
        exclude: package-lock.json
      - id: check-added-large-files
        name: large-files-in-dist
        args: ["--maxkb=200"]
        files: dist/
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
  # Linting
  - repo: https://github.com/NanoSurface-Biomedical/pre-commit-pylint
    rev: "d805cc60bb5290c2f1ca869d5f1d5e2be720f3fa" # pick a git hash / tag to point to
    hooks:
      - id: vuejs-check-no-console-log-statments
        exclude: dist
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.23.0
    hooks:
      - id: eslint
        exclude: (dist/)
        files: \.(vue)|(js)$
        types: [file]
        args: [--fix]
