AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"

# Adapted from: https://github.com/aws-samples/aws-codebuild-samples/blob/master/cloudformation/continuous-integration-pull-request-checks.yml
# to create: aws cloudformation deploy --stack-name=codebuild-frontend-test-utils --parameter-overrides CodeCommitRepoName=frontend_test_utils --template-file=codebuild-formation.yaml --capabilities CAPABILITY_NAMED_IAM

Description: Perform continuous integration pull request checks on a CodeCommit repository with CodeBuild

Parameters:
  CodeCommitRepoName:
    Description: A CodeCommit repository that contains the application code. Must be in same region as this stack.
    Type: String

Resources:
  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - codecommit:GitPull
            Effect: Allow
            Resource: "*"
          - Action:
              - codecommit:GitPush
            Effect: Allow
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:codecommit"
                  - Ref: "AWS::Region"
                  - "*"
                  - Ref: "CodeCommitRepoName"
          - Action:
              - ssm:GetParameters
            Effect: Allow
            Resource:
              - Fn::Join:
                  - "/"
                  - - "arn:aws:ssm:*:*:parameter/CodeBuild"
                    - "general"
                    - "*"
          - Action:
              - kms:Decrypt
            Effect: Allow
            Resource: "arn:aws:kms:*:*:alias/aws/ssm"

      PolicyName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuildPolicy
      Roles:
        - Ref: "CodeBuildRole"
    Type: AWS::IAM::Policy

  CodeBuildProject:
    DependsOn:
      - CodeBuildPolicy
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Description:
        Fn::Join:
          - ""
          - - "CodeBuild Project for "
            - Ref: "AWS::StackName"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0-20.03.13
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: APPLY_TAG
            Type: PLAINTEXT
            Value: "0"
      Name:
        Ref: "CodeCommitRepoName"
      ServiceRole:
        Ref: "CodeBuildRole"
      Source:
        Type: CODECOMMIT
        Location:
          Fn::Join:
            - ""
            - - "https://git-codecommit."
              - Ref: "AWS::Region"
              - ".amazonaws.com/v1/repos/"
              - Ref: "CodeCommitRepoName"
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 30
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      RoleName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuild
    Type: AWS::IAM::Role
